version: '3'

networks:
  wan:
    external: true

services:
  wondercms:
    image: saigneur/wondercms:latest
    restart: unless-stopped
    volumes:
      - /path/to/data/:/var/www/html/
    container_name: wondercms
    ports:
      - 8888:80
    networks:
      - wan
